# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test ENVT pip installation
on: workflow_dispatch

permissions:
  contents: read

jobs:
  Test-ENVT-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python 3.9.20
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.9.20"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ENVT/requirements.txt ]; then pip install -r ENVT/requirements.txt; fi
    - name: Install ENVT
      run: |
        python -m pip install ENVT/.
    - name: Run ENVT
      run: |
        envt --help
